name       : appstream-data
version    : 21
release    : 22
source     :
    - git|https://dev.getsol.us/source/solus-appstream-data.git : v21
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - CC0-1.0
    - GFDL-1.3
component  : desktop.core
summary    : AppStream data for Solus
description: |
    AppStream data for Solus
builddeps  :
    - appstream-glib
install    : |
    DESTDIR="$installdir" appstream-util install solus-1.xml.gz solus-1-icons.tar.gz
    chmod 00755 $installdir/usr/share/app-info/xmls
    chmod 00644 $installdir/usr/share/app-info/xmls/solus-1.xml.gz
    ln -sv solus-1 "$installdir/usr/share/app-info/icons/solus"
