name       : appstream-data
version    : 15
release    : 16
source     :
    - git|https://dev.solus-project.com/source/solus-appstream-data.git : v15
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - CC0-1.0
    - GFDL-1.3
component  : desktop.core
summary    : AppStream data for Solus
description: |
    AppStream data for Solus
builddeps  :
    - appstream-glib
install    : |
    DESTDIR="$installdir" appstream-util install solus-1.xml.gz solus-1-icons.tar.gz
    ln -sv solus-1 "$installdir/usr/share/app-info/icons/solus"
