name       : appstream-data
version    : '2'
release    : 2
source     :
    - https://git.solus-project.com/projects/appstream/snapshot/appstream-2.tar.bz2 : e175a94bab0924490d27acdf4e4984754eab655a91a15ea67116930576dea238
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - CC0-1.0
    - GFDL-1.3
component  : desktop.budgie
summary    : AppStream data for Solus
description: |
    AppStream data for Solus
builddeps  :
    - appstream-glib
install    : |
    DESTDIR="$installdir" appstream-util install solus-1.xml.gz solus-1-icons.tar.gz
    ln -sv solus-1 "$installdir/usr/share/app-info/icons/solus"
