name       : appstream-data
version    : 1
release    : 1
source     :
    - https://git.solus-project.com/projects/appstream/snapshot/appstream-1.tar.bz2 : 5836c2270a8bb12f57d393568f491c19a2ce62cd42cbb2be99aa019140b12a77
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - CC0-1.0
    - GFDL-1.3
component  : desktop.budgie
summary    : AppStream data for Solus
description: |
    AppStream data for Solus
builddeps  :
    - appstream-glib
install    : |
    DESTDIR="$installdir" appstream-util install solus-1.xml.gz solus-1-icons.tar.gz
    ln -sv solus-1 "$installdir/usr/share/app-info/icons/solus"
